# This file is distributed under the same license as the Django package.
#
# Translators:
# crazyzubr <hjcnbckfd@gmail.com>, 2020
# Ivan Khomutov <iskhomutov@gmail.com>, 2017
# Jannis Leidel <jannis@leidel.info>, 2011
# Алексей Борискин <sun.void@gmail.com>, 2012-2015,2022-2024
# Андрей Щуров <shurov9009@gmail.com>, 2016
# Влад Мещеряков <victimofamisery@gmail.com>, 2021
# Bobsans <mr.bobsans@gmail.com>, 2016
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-10-24 05:15+0500\n"
"PO-Revision-Date: 2024-08-07 08:09+0000\n"
"Last-Translator: Алексей Борискин <sun.void@gmail.com>, 2012-2015,2022-2024\n"
"Language-Team: Russian (http://app.transifex.com/django/django/language/"
"ru/)\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || "
"(n%100>=11 && n%100<=14)? 2 : 3);\n"

#: venv/lib/python3.12/site-packages/django/contrib/auth/admin.py:49
msgid "Personal info"
msgstr "Персональная информация"

#: venv/lib/python3.12/site-packages/django/contrib/auth/admin.py:51
msgid "Permissions"
msgstr "Права доступа"

#: venv/lib/python3.12/site-packages/django/contrib/auth/admin.py:62
msgid "Important dates"
msgstr "Важные даты"

#: venv/lib/python3.12/site-packages/django/contrib/auth/admin.py:158
#, python-format
msgid "%(name)s object with primary key %(key)r does not exist."
msgstr "%(name)s с первичным ключом %(key)r не существует."

#: venv/lib/python3.12/site-packages/django/contrib/auth/admin.py:177
msgid "Conflicting form data submitted. Please try again."
msgstr ""
"Отправлены взаимоисключающие данные. Измените данные и попробуйте снова."

#: venv/lib/python3.12/site-packages/django/contrib/auth/admin.py:185
msgid "Password changed successfully."
msgstr "Пароль успешно изменен."

#: venv/lib/python3.12/site-packages/django/contrib/auth/admin.py:187
msgid "Password-based authentication was disabled."
msgstr "Аутентификация по паролю была запрещена."

#: venv/lib/python3.12/site-packages/django/contrib/auth/admin.py:208
#, python-format
msgid "Change password: %s"
msgstr "Изменить пароль: %s"

#: venv/lib/python3.12/site-packages/django/contrib/auth/admin.py:210
#, python-format
msgid "Set password: %s"
msgstr "Задать пароль: %s"

#: venv/lib/python3.12/site-packages/django/contrib/auth/apps.py:16
msgid "Authentication and Authorization"
msgstr "Пользователи и группы"

#: venv/lib/python3.12/site-packages/django/contrib/auth/base_user.py:41
msgid "password"
msgstr "пароль"

#: venv/lib/python3.12/site-packages/django/contrib/auth/base_user.py:42
msgid "last login"
msgstr "последний вход"

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:48
msgid "Invalid password format or unknown hashing algorithm."
msgstr "Неизвестный формат пароля или алгоритм хеширования."

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:56
msgid "No password set."
msgstr "Пароль не задан."

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:59
msgid "Reset password"
msgstr "Сбросить пароль"

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:59
msgid "Set password"
msgstr "Задать пароль"

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:104
msgid "The two password fields didn’t match."
msgstr "Введенные пароли не совпадают."

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:107
msgid ""
"Whether the user will be able to authenticate using a password or not. If "
"disabled, they may still be able to authenticate using other backends, such "
"as Single Sign-On or LDAP."
msgstr ""
"Может ли пользователь аутентифироваться по паролю. Если эта возможность "
"выключена, пользователь всё ещё может аутентифицироваться иными способами, "
"например, Single Sing-On или LDAP, если они сконфигурированы и разрешены."

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:113
#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:258
#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:294
msgid "Password"
msgstr "Пароль"

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:113
msgid "Password confirmation"
msgstr "Подтверждение пароля"

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:126
msgid "Enter the same password as before, for verification."
msgstr "Для подтверждения введите, пожалуйста, пароль ещё раз."

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:133
msgid "Password-based authentication"
msgstr "Аутентификация по паролю"

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:136
msgid "Enabled"
msgstr "Разрешена"

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:136
msgid "Disabled"
msgstr "Запрещена"

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:260
msgid ""
"Raw passwords are not stored, so there is no way to see the user’s password."
msgstr ""
"Мы не храним сырые пароли, поэтому не существует способа посмотреть пароль "
"пользователя."

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:276
msgid ""
"Enable password-based authentication for this user by setting a password."
msgstr ""
"Разрешить аутентификацию по паролю для этого пользователя, задав его пароль."

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:301
#, python-format
msgid ""
"Please enter a correct %(username)s and password. Note that both fields may "
"be case-sensitive."
msgstr ""
"Пожалуйста, введите правильные %(username)s и пароль. Оба поля могут быть "
"чувствительны к регистру."

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:304
msgid "This account is inactive."
msgstr "Эта учетная запись отключена."

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:369
msgid "Email"
msgstr "Адрес электронной почты"

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:472
msgid "New password"
msgstr "Новый пароль"

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:472
msgid "New password confirmation"
msgstr "Подтверждение нового пароля"

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:497
msgid "Your old password was entered incorrectly. Please enter it again."
msgstr "Ваш старый пароль введен неправильно. Пожалуйста, введите его снова."

#: venv/lib/python3.12/site-packages/django/contrib/auth/forms.py:501
msgid "Old password"
msgstr "Старый пароль"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:349
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:442
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:532
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:627
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:678
msgid "algorithm"
msgstr "алгоритм"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:350
msgid "iterations"
msgstr "итерации"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:351
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:448
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:534
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:631
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:679
msgid "salt"
msgstr "соль"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:352
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:449
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:632
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:680
msgid "hash"
msgstr "хэш"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:443
msgid "variety"
msgstr "множество"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:444
msgid "version"
msgstr "версия"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:445
msgid "memory cost"
msgstr "затраты памяти"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:446
msgid "time cost"
msgstr "затраты времени"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:447
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:630
msgid "parallelism"
msgstr "параллелизм"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:533
#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:628
msgid "work factor"
msgstr "рабочий фактор"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:535
msgid "checksum"
msgstr "контрольная сумма"

#: venv/lib/python3.12/site-packages/django/contrib/auth/hashers.py:629
msgid "block size"
msgstr "размер блока"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:63
#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:117
msgid "name"
msgstr "имя"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:67
msgid "content type"
msgstr "тип содержимого"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:69
msgid "codename"
msgstr "кодовое название"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:74
msgid "permission"
msgstr "право"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:75
#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:120
msgid "permissions"
msgstr "права"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:127
msgid "group"
msgstr "группа"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:128
#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:259
msgid "groups"
msgstr "группы"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:250
msgid "superuser status"
msgstr "статус суперпользователя"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:253
msgid ""
"Designates that this user has all permissions without explicitly assigning "
"them."
msgstr "Указывает, что пользователь имеет все права без явного их назначения."

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:262
msgid ""
"The groups this user belongs to. A user will get all permissions granted to "
"each of their groups."
msgstr ""
"Группы, к которым принадлежит данный пользователь. Пользователь получит все "
"права, указанные в каждой из его/её групп."

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:270
msgid "user permissions"
msgstr "права пользователя"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:272
msgid "Specific permissions for this user."
msgstr "Индивидуальные права данного пользователя."

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:346
msgid "username"
msgstr "имя пользователя"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:350
msgid "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
msgstr ""
"Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./"
"+/-/_."

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:354
msgid "A user with that username already exists."
msgstr "Пользователь с таким именем уже существует."

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:357
msgid "first name"
msgstr "имя"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:358
msgid "last name"
msgstr "фамилия"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:359
msgid "email address"
msgstr "адрес электронной почты"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:361
msgid "staff status"
msgstr "статус персонала"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:363
msgid "Designates whether the user can log into this admin site."
msgstr ""
"Отметьте, если пользователь может входить в административную часть сайта."

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:366
msgid "active"
msgstr "активный"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:369
msgid ""
"Designates whether this user should be treated as active. Unselect this "
"instead of deleting accounts."
msgstr ""
"Отметьте, если пользователь должен считаться активным. Уберите эту отметку "
"вместо удаления учётной записи."

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:373
msgid "date joined"
msgstr "дата регистрации"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:382
msgid "user"
msgstr "пользователь"

#: venv/lib/python3.12/site-packages/django/contrib/auth/models.py:383
msgid "users"
msgstr "пользователи"

#: venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py:111
#, python-format
msgid ""
"This password is too short. It must contain at least %(min_length)d "
"character."
msgid_plural ""
"This password is too short. It must contain at least %(min_length)d "
"characters."
msgstr[0] ""
"Введённый пароль слишком короткий. Он должен содержать как минимум "
"%(min_length)d символ."
msgstr[1] ""
"Введённый пароль слишком короткий. Он должен содержать как минимум "
"%(min_length)d символа."
msgstr[2] ""
"Введённый пароль слишком короткий. Он должен содержать как минимум "
"%(min_length)d символов."
msgstr[3] ""
"Введённый пароль слишком короткий. Он должен содержать как минимум "
"%(min_length)d символов."

#: venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py:123
#, python-format
msgid "Your password must contain at least %(min_length)d character."
msgid_plural "Your password must contain at least %(min_length)d characters."
msgstr[0] "Ваш пароль должен содержать как минимум %(min_length)d символ."
msgstr[1] "Ваш пароль должен содержать как минимум %(min_length)d символа."
msgstr[2] "Ваш пароль должен содержать как минимум %(min_length)d символов."
msgstr[3] "Ваш пароль должен содержать как минимум %(min_length)d символов."

#: venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py:206
#, python-format
msgid "The password is too similar to the %(verbose_name)s."
msgstr "Введённый пароль слишком похож на %(verbose_name)s."

#: venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py:213
msgid "Your password can’t be too similar to your other personal information."
msgstr "Пароль не должен быть слишком похож на другую вашу личную информацию."

#: venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py:245
msgid "This password is too common."
msgstr "Введённый пароль слишком широко распространён."

#: venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py:250
msgid "Your password can’t be a commonly used password."
msgstr "Пароль не должен быть слишком простым и распространенным."

#: venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py:261
msgid "This password is entirely numeric."
msgstr "Введённый пароль состоит только из цифр."

#: venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py:266
msgid "Your password can’t be entirely numeric."
msgstr "Пароль не может состоять только из цифр."

#: venv/lib/python3.12/site-packages/django/contrib/auth/templates/registration/password_reset_subject.txt:2
#, python-format
msgid "Password reset on %(site_name)s"
msgstr "Сброс пароля на %(site_name)s"

#: venv/lib/python3.12/site-packages/django/contrib/auth/validators.py:12
msgid ""
"Enter a valid username. This value may contain only unaccented lowercase a-z "
"and uppercase A-Z letters, numbers, and @/./+/-/_ characters."
msgstr ""
"Введите правильное имя пользователя. Это значение может содержать только "
"строчные буквы латиницы a-z без умляутов, прописные буквы A-Z, цифры и "
"символы @/./+/-/_."

#: venv/lib/python3.12/site-packages/django/contrib/auth/validators.py:22
msgid ""
"Enter a valid username. This value may contain only letters, numbers, and "
"@/./+/-/_ characters."
msgstr ""
"Введите правильное имя пользователя. Оно может содержать только буквы, цифры "
"и знаки @/./+/-/_."

#: venv/lib/python3.12/site-packages/django/contrib/auth/views.py:164
msgid "Logged out"
msgstr "Не авторизован"

#: venv/lib/python3.12/site-packages/django/contrib/auth/views.py:224
msgid "Password reset"
msgstr "Восстановление пароля"

#: venv/lib/python3.12/site-packages/django/contrib/auth/views.py:252
msgid "Password reset sent"
msgstr "Письмо с инструкциями по восстановлению пароля отправлено"

#: venv/lib/python3.12/site-packages/django/contrib/auth/views.py:263
msgid "Enter new password"
msgstr "Введите новый пароль"

#: venv/lib/python3.12/site-packages/django/contrib/auth/views.py:335
msgid "Password reset unsuccessful"
msgstr "Ошибка восстановления пароля"

#: venv/lib/python3.12/site-packages/django/contrib/auth/views.py:345
msgid "Password reset complete"
msgstr "Восстановление пароля завершено"

#: venv/lib/python3.12/site-packages/django/contrib/auth/views.py:357
msgid "Password change"
msgstr "Изменение пароля"

#: venv/lib/python3.12/site-packages/django/contrib/auth/views.py:380
msgid "Password change successful"
msgstr "Пароль успешно изменен"
